name: E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run nightly at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
        environment: [development]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'app/package-lock.json'

      - name: Install dependencies
        run: |
          cd app
          npm ci

      - name: Install Playwright Browsers
        run: |
          cd app
          npx playwright install --with-deps ${{ matrix.browser }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: 6.0

      - name: Setup test environment
        run: |
          echo "TEST_ENV=${{ matrix.environment }}" >> $GITHUB_ENV
          echo "CI=true" >> $GITHUB_ENV

      - name: Start application
        run: |
          cd app
          npm run build
          npm run start &
          sleep 30
        env:
          NODE_ENV: production
          PORT: 3009

      - name: Run E2E tests
        run: |
          cd app
          npx playwright test --project=${{ matrix.browser }}
        env:
          TEST_BASE_URL: http://localhost:3009

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results-${{ matrix.browser }}-${{ matrix.environment }}
          path: |
            app/test-results/
            app/playwright-report/
          retention-days: 7

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-screenshots-${{ matrix.browser }}-${{ matrix.environment }}
          path: app/test-results/screenshots/
          retention-days: 3

  slack-notification:
    name: Notify Slack
    runs-on: ubuntu-latest
    needs: e2e-tests
    if: always() && (needs.e2e-tests.result == 'failure')

    steps:
      - name: Send Slack notification
        if: env.SLACK_WEBHOOK_URL != ''
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          text: "E2E tests failed on ${{ github.ref_name }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  performance-tests:
    name: Performance Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || contains(github.event.head_commit.message, '[perf]')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'app/package-lock.json'

      - name: Install dependencies
        run: |
          cd app
          npm ci
          npx playwright install chromium

      - name: Start application
        run: |
          cd app
          npm run build
          npm run start &
          sleep 30

      - name: Run performance tests
        run: |
          cd app
          npx playwright test --grep="@performance"

      - name: Upload performance results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: performance-results
          path: app/test-results/performance/
          retention-days: 14